import assert from 'node:assert/strict';
import test from 'node:test';
import { EventEmitter } from 'node:events';
import { attach, Ledger, MemoryLedgerAdapter, Reconciler } from '../src/index.js';
const now = Date.parse('2026-08-07T12:00:00.000Z');
const clock = () => now;
const intent = (overrides = {}) => ({ actionType: 'CHANNEL_CREATE', targetId: 'target', targetType: 'channel', guildId: 'guild', correlationId: 'intent-1', ...overrides });
const event = (overrides = {}) => ({ actionType: 'CHANNEL_CREATE', targetId: 'target', targetType: 'channel', guildId: 'guild', executorId: 'bot', auditEntryId: 'audit-1', occurredAt: new Date(now).toISOString(), count: 1, ...overrides });

test('ledger writes canonical entry and purges only beyond retention', async () => { const ledger = new Ledger({ clock, idFactory: () => 'generated' }); const entry = await ledger.record(intent({ correlationId: undefined })); assert.equal(entry.correlationId, 'generated'); assert.equal(entry.expiresAt, '2026-08-07T12:02:00.000Z'); await ledger.purge(now + 240001); assert.equal((await ledger.entries()).length, 0); });
test('reconciler consumes exact entries at inclusive timing edge', async () => { const ledger = new Ledger({ clock }); await ledger.record(intent({ timestamp: now - 120000 })); const report = await new Reconciler({ ledger, clock }).reconcile(event()); assert.equal(report, null); assert.equal((await ledger.entries()).length, 0); });
test('reconciler reports deterministic partial and expired near misses', async () => { const ledger = new Ledger({ clock }); await ledger.record(intent({ targetId: 'other' })); let report = await new Reconciler({ ledger, clock }).reconcile(event()); assert.equal(report.ledger.state, 'partial'); assert.equal(report.confidence, 'medium'); const oldLedger = new Ledger({ clock }); await oldLedger.record(intent({ targetId: 'other', expiresAt: now - 1 })); report = await new Reconciler({ ledger: oldLedger, clock }).reconcile(event()); assert.equal(report.ledger.state, 'expired'); });
test('collapsed burst consumes action intents regardless of individual targets', async () => { const ledger = new Ledger({ clock }); for (let index = 0; index < 3; index++) await ledger.record(intent({ actionType: 'MEMBER_MOVE', targetId: `member-${index}`, correlationId: `move-${index}` })); const reconciler = new Reconciler({ ledger, clock }); assert.equal(await reconciler.reconcile(event({ actionType: 'MEMBER_MOVE', targetId: 'member-0', count: 3 })), null); assert.equal((await ledger.entries()).length, 0); });
test('under-ledgered collapsed burst reports drift', async () => { const ledger = new Ledger({ clock }); await ledger.record(intent({ actionType: 'MESSAGE_DELETE', targetId: 'x' })); const report = await new Reconciler({ ledger, clock }).reconcile(event({ actionType: 'MESSAGE_DELETE', count: 2 })); assert.equal(report.kind, 'drift'); assert.equal(report.event.count, 2); });
test('all representative coverage actions reconcile exactly', async () => { const actions = ['GUILD_UPDATE','CHANNEL_DELETE','CHANNEL_OVERWRITE_UPDATE','MEMBER_KICK','MEMBER_BAN_ADD','ROLE_UPDATE','INVITE_DELETE','WEBHOOK_CREATE','EMOJI_DELETE','STICKER_UPDATE','INTEGRATION_DELETE','STAGE_INSTANCE_CREATE','GUILD_SCHEDULED_EVENT_UPDATE','THREAD_DELETE','APPLICATION_COMMAND_PERMISSION_UPDATE','AUTO_MODERATION_RULE_CREATE','ONBOARDING_UPDATE','VOICE_CHANNEL_STATUS_UPDATE','GUILD_SOUNDBOARD_SOUND_CREATE','GUILD_EXPRESSION_DELETE','MESSAGE_PIN']; for (const actionType of actions) { const ledger = new Ledger({ clock }); await ledger.record(intent({ actionType, correlationId: actionType })); assert.equal(await new Reconciler({ ledger, clock }).reconcile(event({ actionType })), null, actionType); } });
test('mocked gateway detects rogue audit action and self message action', async () => { const client = new EventEmitter(); client.user = { id: 'bot' }; const reports = []; const parity = attach(client, { clock, strategies: [{ send: async report => reports.push(report) }] }); await parity.intent(intent()); client.emit('guildAuditLogEntryCreate', { id: 'audit-ok', action: 10, targetId: 'target', executorId: 'bot', createdTimestamp: now }, { id: 'guild' }); await new Promise(resolve => setImmediate(resolve)); client.emit('guildAuditLogEntryCreate', { id: 'audit-rogue', action: 10, targetId: 'rogue', executorId: 'bot', createdTimestamp: now }, { id: 'guild' }); client.emit('messageCreate', { id: 'message-rogue', guildId: 'guild', author: { id: 'bot' }, createdTimestamp: now }); await new Promise(resolve => setImmediate(resolve)); assert.equal(reports.length, 2); assert.equal(reports[0].event.targetId, 'rogue'); assert.equal(reports[1].event.actionType, 'MESSAGE_CREATE'); parity.detach(); });
test('500 concurrent exact audit entries leave no ledger memory', async () => { const ledger = new Ledger({ clock }); const reconciler = new Reconciler({ ledger, clock }); await Promise.all([...Array(500)].map((_, index) => ledger.record(intent({ targetId: String(index), correlationId: `load-${index}` })))); const results = await Promise.all([...Array(500)].map((_, index) => reconciler.reconcile(event({ targetId: String(index), auditEntryId: `audit-${index}` })))); assert.ok(results.every(result => result === null)); assert.equal((await ledger.entries()).length, 0); });

test('sqlite adapter persists ledger entries through its adapter contract', async () => { const { SqliteLedgerAdapter } = await import('../src/index.js'); const adapter = new SqliteLedgerAdapter(); const ledger = new Ledger({ adapter, clock }); await ledger.record(intent()); assert.equal((await ledger.entries())[0].correlationId, 'intent-1'); await ledger.remove('intent-1'); assert.equal((await ledger.entries()).length, 0); adapter.close(); });
